[package]
name = "celaut-explorer"
version = "0.1.0"
authors = ["Nat Knight <nathaniel.ep@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen="=0.2.33"
celaut = {path="../celaut"}

[dev-dependencies]
wasm-bindgen-cli="=0.2.33"
